# TODO: can we assume that the subworkflow order will always be kept?
subworkflow data_retrieval:
    workdir:
        'TESTING_DR'
    snakefile:
        'rules/data_retrieval.smk'
    configfile:
        'config/data_retrieval.config.yaml'


subworkflow vpipe_wrapper:
    workdir:
        'TESTING_VP'
    snakefile:
        'rules/vpipe_wrapper.smk'
    configfile:
        'config/vpipe_wrapper.config.yaml'


subworkflow visualize_results:
    workdir:
        'TESTING_VR'
    snakefile:
        'rules/visualize_results.smk'
    configfile:
        'config/visualize_results.config.yaml'


rule all:
    input:
        data_retrieval('processed_fastq_data'),
        vpipe_wrapper('vcf_PE'),
        visualize_results('results/top_samples_extended.txt'),
        visualize_results('plots/snv_coverage_plot.pdf')
