# TODO: can we assume that the subworkflow order will always be kept?
subworkflow data_retrieval:
    workdir:
        '../results/pipeline_run__data_retrieval'
    snakefile:
        'rules/data_retrieval.smk'
    configfile:
        'config/data_retrieval.config.yaml'


subworkflow vpipe_wrapper_SE:  # V-pipe run for single-end reads
    workdir:
        '../results/pipeline_run__vpipe_wrapper_SE'
    snakefile:
        'rules/vpipe_wrapper.smk'
    configfile:
        'config/vpipe_wrapper_se.config.yaml'


subworkflow vpipe_wrapper_PE:  # V-pipe run for paired-end reads
    workdir:
        '../results/pipeline_run__vpipe_wrapper_PE'
    snakefile:
        'rules/vpipe_wrapper.smk'
    configfile:
        'config/vpipe_wrapper_pe.config.yaml'


subworkflow visualize_results:
    workdir:
        '../results/pipeline_run__visualize_results'
    snakefile:
        'rules/visualize_results.smk'
    configfile:
        'config/visualize_results.config.yaml'


rule all:
    input:
        data_retrieval('processed_fastq_data'),
        vpipe_wrapper_SE('vcf_files'),
        vpipe_wrapper_PE('vcf_files'),
        visualize_results('results/top_samples_extended.txt'),
        visualize_results('plots/snv_coverage_plot.pdf')
